### ISSUE TITLE
QtWebEngine for 5.15-23.08 needed 

### ISSUE THREAD

**Issue by hfiguiere** [flathub/io.qt.qtwebengine.BaseApp#308]
QtWebEngine for 5.15-23.08 is needed.

Note: it doesn't build out of the box, Python gets in the way, again.

**Comment by hfiguiere** [comment]
```
FAILED: gen/services/metrics/public/cpp/ukm_builders.cc gen/services/metrics/public/cpp/ukm_builders.h gen/services/metrics/public/cpp/ukm_decode.cc gen/services/metrics/public/cpp/ukm_decode.h 
/usr/bin/python ../../../../src/3rdparty/chromium/tools/metrics/ukm/gen_builders.py --input ../../../../src/3rdparty/chromium/tools/metrics/ukm/ukm.xml --output gen/services/metrics/public/cpp
Traceback (most recent call last):
  File "/run/build/qt5-qtwebengine/_flatpak_build/src/core/release/../../../../src/3rdparty/chromium/tools/metrics/ukm/gen_builders.py", line 59, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/run/build/qt5-qtwebengine/_flatpak_build/src/core/release/../../../../src/3rdparty/chromium/tools/metrics/ukm/gen_builders.py", line 27, in main
    data = ReadFilteredData(args.input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/build/qt5-qtwebengine/_flatpak_build/src/core/release/../../../../src/3rdparty/chromium/tools/metrics/ukm/gen_builders.py", line 48, in ReadFilteredData
    data = ukm_model.UKM_XML_TYPE.Parse(ukm_file.read())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/build/qt5-qtwebengine/src/3rdparty/chromium/tools/metrics/ukm/../common/models.py", line 439, in Parse
    return self._ParseMinidom(input_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/build/qt5-qtwebengine/src/3rdparty/chromium/tools/metrics/ukm/../common/models.py", line 418, in _ParseMinidom
    return self.root_type.Unmarshall(root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/build/qt5-qtwebengine/src/3rdparty/chromium/tools/metrics/ukm/../common/models.py", line 323, in Unmarshall
    obj[child.attr] = [
                      ^
  File "/run/build/qt5-qtwebengine/src/3rdparty/chromium/tools/metrics/ukm/../common/models.py", line 324, in <listcomp>
    child.node_type.Unmarshall(n) for n in nodes]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/build/qt5-qtwebengine/src/3rdparty/chromium/tools/metrics/ukm/../common/models.py", line 302, in Unmarshall
    if not re.match(attr_re, attr_val):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 166, in match
    return _compile(pattern, flags).match(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 982, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 457, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 843, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 1

```

**Comment by guihkx** [comment]
Done in #314?

**Comment by bbhtt** [comment]
Was waiting for it to be published, but now it is available 

```
flatpak remote-info --system flathub io.qt.qtwebengine.BaseApp//5.15-23.08
        ID: io.qt.qtwebengine.BaseApp
       Ref: app/io.qt.qtwebengine.BaseApp/x86_64/5.15-23.08
      Arch: x86_64
    Branch: 5.15-23.08
Collection: org.flathub.Stable
  Download: 132.9 MB
 Installed: 384.3 MB
   Runtime: org.kde.Platform/x86_64/5.15-23.08
       Sdk: org.kde.Sdk/x86_64/5.15-23.08

    Commit: 40f079b41ace5618942b365f2709f3d871cf1baeb1f51708f9d7ff96144b6823
   Subject: Run workflow on branch/23.08 (095a12b6)
      Date: 2023-10-16 14:46:26 +0000
```

**Comment by bbhtt** [comment]
https://github.com/flathub/flathub/issues/4612
